name: Run tests

on:
  push:
    branches:
      - master
  schedule:
  - cron: '0 2 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: true

jobs:
  test_schedule:
    name: Test schedule
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Set up Julia"
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.10'
    - name: "Install Jupyter"
      run: pip3 install notebook
    - name: "Install julia pre-requisites"
      run: |
        julia -e '
          using Pkg
          Pkg.add("IJulia")
          Pkg.add("Oscar")
          Pkg.add("BenchmarkTools")
          Pkg.add("GraphRecipes")
          Pkg.add("Graphs")
          Pkg.add("Interact")
          Pkg.add("Plots")'
    - name: "Run python script"
      run: python3 scraper.py 
